A set of scripts to install HubZero
===================================

This project is a set of scripts for installing [HubZero](https://hubzero.org) onto a virtual machine
running on the Nectar cloud, using [Heat](https://support.rc.nectar.org.au/docs/heat)

# NB: This is a work in progress! #

To use these scripts you need to have the Heat command line client installed. Instructions for installing and using
the command line tools on the NeCTAR cloud [are found here](https://support.rc.nectar.org.au/docs/installing-command-line-tools).

You also need to know a little bit about [Heat](https://support.rc.nectar.org.au/docs/heat) if you are
going to customize the default paramater values...

Once the command line tools are installed, the following steps will get you up and running:

```bash
# Clone the repository
git clone https://github.com/MartinPaulo/puppet_hub_zero.git

# Copy the environment template in the heat subdirectory, say to a file named 'environment.yaml'
cp heat/environment_template.yaml heat/environment.yaml

# Edit the file and provide any required parameters.
# Also put in replacement values for any of the default parameter values that are not acceptable.
# These parameters and the defaults are described in the heat template, heat/hubzero.yaml
vi heat/environment.yaml

# Launch the heat template
heat stack-create --template-file=heat/hubzero.yaml --environment-file=heat/environment.yaml hubzero_1_3

# wait for a while...
# TODO: email the user when the install is complete...
```

Once complete, the passwords and users created by the ldap installation have been written to the file:

```bash
/root/ldap_details.txt
```

If installing version 1.1, once the installation is complete, go to the administrator section of your site
(/administrator), go to Site->Maintenance->LDAP and press the Export Users and Export Groups buttons
in order to export all the CMS users and groups

Tasks still to be done:
- Email the user when the install is complete
- Email needs to be properly configured ( *Check: must not relay email!* )
- Need to move the users home directories to the larger mounted transient storage.
- telequotad not yet added to the installation
- rapture not yet added to the installation
- submit not yet added to the installation
- The DNS entry and matching records need to be set up manually. Instructions have to be written.

Known issues:
- The LDAP installation on version 1.1 returns an error: needs investigation. See the open-ldap module for more.
- The maxwell service create template execution seems thoroughly broken in 1.1 and 1.2. This would appear to
  be a HubZero Issue
- The email doesn't send mail successfully, as sites such as google don't trust it (not surprising).
- The [admin url](https://hubzero.org/wiki/HubAdministrationGuide/Login) doesn't let you log in using the password
  generated by the LDAP program...
- The 1.1, the 1.2 and 1.3 forge install gives the following error:

  ```bash
  Exec[initialize forge]/returns: enabling hubzero-forge#033[0m
  Exec[initialize forge]/returns: checking user 'apps'#033[0m
  Exec[initialize forge]/returns: creating user 'apps'#033[0m
  Exec[initialize forge]/returns: creating homedir: /home/example/apps#033[0m
  Exec[initialize forge]/returns: Traceback (most recent call last):#033[0m
  Exec[initialize forge]/returns:   File "/usr/bin/hzcms", line 4855, in <module>#033[0m
  Exec[initialize forge]/returns:     args.func(args)#033[0m
  Exec[initialize forge]/returns:   File "/usr/bin/hzcms", line 2227, in _forgeConfigure#033[0m
  Exec[initialize forge]/returns:     forgeConfigure(args.enable)#033[0m
  Exec[initialize forge]/returns:   File "/usr/bin/hzcms", line 2249, in forgeConfigure#033[0m
  Exec[initialize forge]/returns:     skipCreateGroup = True)#033[0m
  Exec[initialize forge]/returns:   File "/usr/lib/python2.6/dist-packages/hubzero/utilities/user.py", line 493, in addhubuser#033[0m
  Exec[initialize forge]/returns:     add_ldap_user(username, gecos, pw, uidNumber, homeDir, loginShell, gid, gidNumber)#033[0m
  Exec[initialize forge]/returns:   File "/usr/lib/python2.6/dist-packages/hubzero/utilities/user.py", line 322, in add_ldap_user#033[0m
  Exec[initialize forge]/returns:     l.add_s(dn, ldif)#033[0m
  Exec[initialize forge]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 194, in add_s#033[0m
  Exec[initialize forge]/returns:     return self.result(msgid,all=1,timeout=self.timeout)#033[0m
  Exec[initialize forge]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 422, in result#033[0m
  Exec[initialize forge]/returns:     res_type,res_data,res_msgid = self.result2(msgid,all,timeout)#033[0m
  Exec[initialize forge]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 426, in result2#033[0m
  Exec[initialize forge]/returns:     res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)#033[0m
  Exec[initialize forge]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 432, in result3#033[0m
  Exec[initialize forge]/returns:     ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)#033[0m
  Exec[initialize forge]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 96, in _ldap_call#033[0m
  Exec[initialize forge]/returns:     result = func(*args,**kwargs)#033[0m
  Exec[initialize forge]/returns: ldap.INVALID_DN_SYNTAX: {'info': 'invalid DN', 'desc': 'Invalid DN syntax'}#033[0m
  [1;31mError: /usr/bin/hzcms configure forge --enable returned 1 instead of one of [0]#033[0m
  ```

- The 1.1, the 1.2 and 1.3 maxwell service gives the following (probably related) error:

  ```bash
  Exec[enable maxwell]/returns: Traceback (most recent call last):#033[0m
  Exec[enable maxwell]/returns:   File "/usr/bin/hzcms", line 4855, in <module>#033[0m
  Exec[enable maxwell]/returns:     args.func(args)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/bin/hzcms", line 2576, in _mwServiceConfigure#033[0m
  Exec[enable maxwell]/returns:     mwServiceConfigure(args.enable)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/bin/hzcms", line 2702, in mwServiceConfigure#033[0m
  Exec[enable maxwell]/returns:     hubzero.utilities.group.addhubgroup("network", "network")#033[0m
  Exec[enable maxwell]/returns:   File "/usr/lib/python2.6/dist-packages/hubzero/utilities/group.py", line 259, in addhubgroup#033[0m
  Exec[enable maxwell]/returns:     add_ldap_group(groupName, description, gidNumber)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/lib/python2.6/dist-packages/hubzero/utilities/group.py", line 167, in add_ldap_group#033[0m
  Exec[enable maxwell]/returns:     l.add_s(dn, ldif)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 194, in add_s#033[0m
  Exec[enable maxwell]/returns:     return self.result(msgid,all=1,timeout=self.timeout)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 422, in result#033[0m
  Exec[enable maxwell]/returns:     res_type,res_data,res_msgid = self.result2(msgid,all,timeout)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 426, in result2#033[0m
  Exec[enable maxwell]/returns:     res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 432, in result3#033[0m
  Exec[enable maxwell]/returns:     ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)#033[0m
  Exec[enable maxwell]/returns:   File "/usr/lib/python2.6/dist-packages/ldap/ldapobject.py", line 96, in _ldap_call#033[0m
  Exec[enable maxwell]/returns:     result = func(*args,**kwargs)#033[0m
  Exec[enable maxwell]/returns: ldap.INVALID_DN_SYNTAX: {'info': 'invalid DN', 'desc': 'Invalid DN syntax'}#033[0m
  [1;31mError: /usr/bin/hzcms configure mw-service --enable returned 1 instead of one of [0]#033[0m
  ```

- Hence the install of the 1.1, the 1.2 and the 1.3 maxwell client is skipped.
- The 1.1, the 1.2 and 1.3 workspace install gives the following error:

  ```bash
  Exec[initialize workspace]/returns: Traceback (most recent call last):#033[0m
  Exec[initialize workspace]/returns:   File "/usr/bin/hubzero-app", line 696, in <module>#033[0m
  Exec[initialize workspace]/returns:     Hubzero_App().dispatch()#033[0m
  Exec[initialize workspace]/returns:   File "/usr/bin/hubzero-app", line 511, in dispatch#033[0m
  Exec[initialize workspace]/returns:     self.changeuid()#033[0m
  Exec[initialize workspace]/returns:   File "/usr/bin/hubzero-app", line 492, in changeuid#033[0m
  Exec[initialize workspace]/returns:     _,_,uid,gid,_,_,_ = pwd.getpwnam("apps")#033[0m
  Exec[initialize workspace]/returns: KeyError: 'getpwnam(): name not found: apps'#033[0m
  [1;31mError: /usr/bin/hubzero-app install --publish /usr/share/hubzero/apps/workspace-1.3.hza returned 1 instead of one of [0]#033[0m
  ```